name: viciphone
region: nyc3
services:
  - name: viciphone-web
    environment_slug: php
    instance_size_slug: apps-s-1vcpu-1gb
    instance_count: 1
    source_dir: Source
    http_port: 8080
    run_command: heroku-php-apache2 Source/
    routes:
      - path: /
    envs:
      - key: PHONE_LOGIN
        scope: RUN_TIME
        value: ""
      - key: PHONE_PASS
        scope: RUN_TIME
        value: ""
      - key: SERVER_IP
        scope: RUN_TIME
        value: ""
      - key: WS_SERVER
        scope: RUN_TIME
        value: ""
      - key: CODECS
        scope: RUN_TIME
        value: ""
      - key: OPTIONS
        scope: RUN_TIME
        value: ""
      - key: DEBUG_ENABLED
        scope: RUN_TIME
        value: "0"
